name: CI

on:
  - push
  - pull_request

jobs:
  nix:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix build
